// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_179661d3e7528951, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// Normal data
type NormalData struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NormalData) Reset()         { *m = NormalData{} }
func (m *NormalData) String() string { return proto.CompactTextString(m) }
func (*NormalData) ProtoMessage()    {}
func (*NormalData) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_179661d3e7528951, []int{1}
}
func (m *NormalData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NormalData.Unmarshal(m, b)
}
func (m *NormalData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NormalData.Marshal(b, m, deterministic)
}
func (dst *NormalData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NormalData.Merge(dst, src)
}
func (m *NormalData) XXX_Size() int {
	return xxx_messageInfo_NormalData.Size(m)
}
func (m *NormalData) XXX_DiscardUnknown() {
	xxx_messageInfo_NormalData.DiscardUnknown(m)
}

var xxx_messageInfo_NormalData proto.InternalMessageInfo

func (m *NormalData) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// Peer info
type PeerInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addrs                []string `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerInfo) Reset()         { *m = PeerInfo{} }
func (m *PeerInfo) String() string { return proto.CompactTextString(m) }
func (*PeerInfo) ProtoMessage()    {}
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_179661d3e7528951, []int{2}
}
func (m *PeerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerInfo.Unmarshal(m, b)
}
func (m *PeerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerInfo.Marshal(b, m, deterministic)
}
func (dst *PeerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerInfo.Merge(dst, src)
}
func (m *PeerInfo) XXX_Size() int {
	return xxx_messageInfo_PeerInfo.Size(m)
}
func (m *PeerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PeerInfo proto.InternalMessageInfo

func (m *PeerInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PeerInfo) GetAddrs() []string {
	if m != nil {
		return m.Addrs
	}
	return nil
}

// Peer data
type PeerData struct {
	Peers                []*PeerInfo `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PeerData) Reset()         { *m = PeerData{} }
func (m *PeerData) String() string { return proto.CompactTextString(m) }
func (*PeerData) ProtoMessage()    {}
func (*PeerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_179661d3e7528951, []int{3}
}
func (m *PeerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerData.Unmarshal(m, b)
}
func (m *PeerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerData.Marshal(b, m, deterministic)
}
func (dst *PeerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerData.Merge(dst, src)
}
func (m *PeerData) XXX_Size() int {
	return xxx_messageInfo_PeerData.Size(m)
}
func (m *PeerData) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerData.DiscardUnknown(m)
}

var xxx_messageInfo_PeerData proto.InternalMessageInfo

func (m *PeerData) GetPeers() []*PeerInfo {
	if m != nil {
		return m.Peers
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "pb.Message")
	proto.RegisterType((*NormalData)(nil), "pb.NormalData")
	proto.RegisterType((*PeerInfo)(nil), "pb.PeerInfo")
	proto.RegisterType((*PeerData)(nil), "pb.PeerData")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_message_179661d3e7528951) }

var fileDescriptor_message_179661d3e7528951 = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8f, 0xcd, 0x4e, 0xc7, 0x20,
	0x10, 0xc4, 0x03, 0xb5, 0xd6, 0xae, 0xd5, 0x03, 0xf1, 0xc0, 0x91, 0x70, 0x30, 0x9c, 0x88, 0x1f,
	0xaf, 0xe0, 0xc5, 0x83, 0xc6, 0xf0, 0x06, 0x5b, 0x59, 0x4d, 0x13, 0x0b, 0x04, 0x78, 0xff, 0x98,
	0x3f, 0xb4, 0xb7, 0x99, 0xd9, 0x9d, 0x5f, 0x32, 0x70, 0xb7, 0x53, 0x29, 0xf8, 0x4b, 0x36, 0xe5,
	0x58, 0xa3, 0xe0, 0x69, 0xd5, 0xcf, 0x30, 0x7d, 0xf4, 0x50, 0x08, 0xb8, 0x0a, 0xb8, 0x93, 0x64,
	0x8a, 0x99, 0xd9, 0x35, 0x7d, 0xc9, 0x3c, 0x56, 0x94, 0x5c, 0x31, 0xb3, 0xb8, 0xa6, 0xf5, 0x23,
	0xc0, 0x67, 0xcc, 0x3b, 0xfe, 0xbd, 0x61, 0x45, 0x21, 0x61, 0xfa, 0x8e, 0xa1, 0x52, 0xa8, 0x47,
	0xf1, 0xb4, 0xfa, 0x09, 0x6e, 0xbe, 0x88, 0xf2, 0x7b, 0xf8, 0x89, 0xe2, 0x1e, 0xf8, 0xe6, 0x8f,
	0x07, 0xbe, 0x79, 0xf1, 0x00, 0x23, 0x7a, 0x9f, 0x8b, 0xe4, 0x6a, 0x30, 0xb3, 0xeb, 0x46, 0xdb,
	0xde, 0x68, 0x5c, 0x0d, 0x63, 0x22, 0xca, 0x45, 0x32, 0x35, 0x98, 0xdb, 0x97, 0xc5, 0xa6, 0xd5,
	0x9e, 0x38, 0xd7, 0x4f, 0xeb, 0x75, 0xdb, 0xf1, 0xfa, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x3e,
	0xbc, 0xe6, 0xd8, 0x00, 0x00, 0x00,
}
